wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.27.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1680132379.956841
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.14.0
      6: 4.27.3
      8:
      - 5
